### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by muratbuldu**
Backend and frontend is created for examples endpoint.

### CODE REVIEW

**Review by fahricansanli — COMMENTED** [review]
In the testing part, it is better to have more appropriate and meaningful function names.

**Comment by muratbuldu** [comment]
Testing part is corrected.

**Review by yavuzDemir21 — APPROVED** [review]
This is a better way to let others understand your functions. Your change is up to expectations, perfect!

**Review by fahricansanli — APPROVED** [review]

**Review by yavuzDemir21 — COMMENTED** [review]
Endpoint "example" is a nice thought feature, well done mate.

**Review by yavuzDemir21 — APPROVED** [review]
What you write is completely fine and up to our standarts thanks mate!

**Pull request merged**
